server:
  port: ":8080"
jwt:
  secret: "your-super-secret-key-should-be-changed"
database:
  # PostgreSQL Data Source Name (DSN)
  dsn: "postgres://user:password@localhost:5432/workout_db?sslmode=disable"
